import qrcode
from io import BytesIO

class InvoiceBranding:

    COMPANY_NAME = "DreamVille Solutions"

    COMPANY_EMAIL = "billing@dreamville.com"

    COMPANY_PHONE = "+265 123 456 678"

    COMPANY_WEBSITE = "www.dreamville.com"

    PRIMARY_COLOR = "#E0E2E8"

    TERMS = """
    Payment is due within 7 days.
    Thank you for your business.
    """

    FOOTER_TEXT = (
        "Generated by Smart Invoice System"
    )




class QRCodeGenerator:

    @staticmethod
    def generate(invoice):

        qr_data = f"""
        Invoice: {invoice.invoice_number}
        Customer: {invoice.customer_name}
        Total: {invoice.total}
        """

        qr = qrcode.make(qr_data)

        path = (
            f"media/branding/qr_codes/"
            f"{invoice.invoice_number}.png"
        )
        
        buffer = BytesIO()


        qr.save(buffer,format="PNG")
        buffer.seek(0)

        return buffer