# Generated by Django 6.0.5 on 2026-05-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_file', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='invoice_archive',
            field=models.FileField(blank=True, null=True, upload_to='invoice_archives/'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('PROCESSING', 'processing'), ('PROCESSED', 'processed'), ('FAILED', 'failed')], default='PENDING', max_length=20),
        ),
    ]
