# Generated by Django 6.0.5 on 2026-05-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_file', '0003_uploadedfile_invoice_archive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='errors_field',
            field=models.TextField(blank=True, null=True),
        ),
    ]
