# Generated by Django 6.0.5 on 2026-05-27 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_file', '0004_uploadedfile_errors_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='errors_field',
            new_name='errors_msg',
        ),
    ]
