# Generated by Django 6.0.5 on 2026-05-29 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_file', '0005_rename_errors_field_uploadedfile_errors_msg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='errors_msg',
            new_name='error_message',
        ),
    ]
