# Generated by Django 6.0.5 on 2026-05-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_file', '0006_rename_errors_msg_uploadedfile_error_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('processed', 'processed'), ('failed', 'failed')], default='pending', max_length=20),
        ),
    ]
