# Generated by Django 6.0.5 on 2026-06-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_file', '0007_alter_uploadedfile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
