# Generated by Django 6.0.5 on 2026-06-02 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_file', '0008_uploadedfile_is_archived'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='is_archived',
            new_name='is_hidden',
        ),
    ]
