# Generated by Django 6.0.5 on 2026-06-04 20:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_file', '0009_rename_is_archived_uploadedfile_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
