# Generated by Django 6.0.5 on 2026-06-04 20:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_file', '0010_uploadedfile_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
