# Generated by Django 6.0.5 on 2026-05-22 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoice', '0001_initial'),
        ('uploaded_file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='uploaded_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='uploaded_file.uploadedfile'),
        ),
    ]
