# Generated by Django 6.0.5 on 2026-05-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_archive',
            field=models.FileField(blank=True, null=True, upload_to='invoice_archives/'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
