# Generated by Django 6.0.5 on 2026-05-27 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_invoice_invoice_archive_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_archive',
        ),
    ]
